### ISSUE TITLE
Issues building webpage. 

### ISSUE THREAD

**Issue by NikeNano** [leptos-rs/leptos-website#17]
Is it expected to work on MacOX? The build dont work and I dont understand the error at all?  Runing: `cargo leptos watch`
```
error[E0425]: cannot find function, tuple struct or tuple variant `Ok` in this scope
    --> /Users/niklashansson/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.183/src/private/ser.rs:1355:9
     |
1355 |         Ok(())
     |         ^^ not found in this scope

Some errors have detailed explanations: E0405, E0412, E0425, E0432, E0433, E0463, E0531.
error: could not compile `serde` (lib) due to 5097 previous errors
      Notify watching folders style, public, src
```

Tried with docker as well but then I got: 

`docker run -p 8080:8080 blog`

```
listening on http://0.0.0.0:8080
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/femark-0.1.4/src/tree_sitter_collection.rs:50:6:
called `Result::unwrap()` on an `Err` value: QueryError { row: 63, column: 24, offset: 1711, message: "", kind: NodeType }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1313:25:
Lazy instance has previously been poisoned
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1313:25:
Lazy instance has previously been poisoned
thread '<unnamed>' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.18.0/src/lib.rs:1313:25:
Lazy instance has previously been poisoned
```

Would love to get this to work and fork of to try to build a webpage ... 

Thank you!!

**Comment by NikeNano** [comment]
Solved after following these steps: https://github.com/leptos-rs/start#installing-additional-tools
